#
#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/smartinventory
#    username: vinod_mudavath
#    password: Mangi@143
#  jpa:
#    database-platform: org.hibernate.dialect.MySQL8Dialect
#    hibernate:
#      ddl-auto: update    # use flyway for schema; use 'update' only for dev
#    show-sql: ${SPRING_JPA_SHOW_SQL:false}
#
#    properties:
#      hibernate:
#        format_sql: true
#  flyway:
#    enabled: false   # disable to avoid Unsupported Database error and unblock startup
#
#server:
#  port: ${SERVER_PORT:8080}
#
#jwt:
#  secret: ${JWT_SECRET:change_this_to_a_long_random_secret_string_at_least_32_chars}
#  expiration: ${JWT_EXPIRATION:86400000}
#
#razorpay:
#  keyId: rzp_test_Rf7lpVBIJ5RDtA
#  keySecret: cnuOFPm7odFAJllVOIyltLhd
#

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update   # for dev; use migration tool for prod
    show-sql: ${SPRING_JPA_SHOW_SQL:false}
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: false   # disable if not using migrations

server:
  port: ${PORT:8080}

jwt:
  secret: ${JWT_SECRET:change_this_to_a_long_random_secret_string_at_least_32_chars}
  expiration: ${JWT_EXPIRATION:86400000}

razorpay:
  keyId: ${RAZORPAY_KEY_ID}
  keySecret: ${RAZORPAY_KEY_SECRET}

#
#spring:
#  datasource:
#    url: ${SPRING_DATASOURCE_URL}         # e.g., jdbc:mysql://localhost:3306/your_db_name
#    username: ${SPRING_DATASOURCE_USERNAME}
#    password: ${SPRING_DATASOURCE_PASSWORD}
#    driver-class-name: com.mysql.cj.jdbc.Driver
#
#  jpa:
#    database-platform: org.hibernate.dialect.MySQL8Dialect
#    hibernate:
#      ddl-auto: update   # for dev; use migration tool for prod
#    show-sql: ${SPRING_JPA_SHOW_SQL:false}
#    properties:
#      hibernate:
#        format_sql: true
#
#  flyway:
#    enabled: false   # disable if not using migrations
#
#server:
#  port: ${PORT:8080}
#
#jwt:
#  secret: ${JWT_SECRET:change_this_to_a_long_random_secret_string_at_least_32_chars}
#  expiration: ${JWT_EXPIRATION:86400000}
#
#razorpay:
#  keyId: ${RAZORPAY_KEY_ID}
#  keySecret: ${RAZORPAY_KEY_SECRET}
